import { useEffect, useState } from 'react'
import type { Announcement, Faculty, School } from './types'
import { getAnnouncements, getFaculty, getSchools } from './data/repository'
import { signIn } from './lib/firebase'
import LoginScreen from './components/LoginScreen'
import SchoolSelection from './components/SchoolSelection'
import Dashboard from './components/Dashboard'
import FacultyDirectory from './components/FacultyDirectory'
import Announcements from './components/Announcements'
type View = 'login' | 'schools' | 'dashboard' | 'directory' | 'announcements'
export default function App() { const [view, setView] = useState<View>('login'); const [school, setSchool] = useState<School | null>(null); const [schools, setSchools] = useState<School[]>([]); const [faculty, setFaculty] = useState<Faculty[]>([]); const [announcements, setAnnouncements] = useState<Announcement[]>([]); useEffect(() => { getSchools().then(setSchools) }, []); const select = (s: School) => { setSchool(s); setView('dashboard') }; useEffect(() => { if (school) { getFaculty(school.id).then(setFaculty); getAnnouncements(school.id).then(setAnnouncements) } }, [school]); if (view === 'login') return <LoginScreen onLogin={async (identifier, password) => { await signIn(identifier, password); setView('schools') }} />; if (view === 'schools') return <SchoolSelection schools={schools} onSelect={select} />; const selected = school ?? schools[0]; if (!selected) return null; if (view === 'directory') return <FacultyDirectory school={selected} faculty={faculty} onBack={() => setView('dashboard')} onAnnouncements={() => setView('announcements')} />; if (view === 'announcements') return <Announcements school={selected} announcements={announcements} onBack={() => setView('dashboard')} />; return <Dashboard school={selected} faculty={faculty} announcements={announcements} onDirectory={() => setView('directory')} onAnnouncements={() => setView('announcements')} /> }
